apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx # k get ingressclass
  rules:
    - http:
        paths:
        - backend:
            service:
              name: nginx
              port:
                number: 80
          path: /nginx(/|$)(.*)
          pathType: ImplementationSpecific
    - http:
        paths:
        - backend:
            service:
              name: httpd
              port:
                number: 80
          path: /httpd(/|$)(.*)
          pathType: ImplementationSpecific