apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
  - hosts:
      - "*.kelsen.com"
    secretName: secret
  ingressClassName: nginx # k get ingressclass
  rules:
  - host: nginx.kelsen.com
    http:
      paths:
      - backend:
          service:
            name: nginx
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  - host: httpd.kelsen.com
    http:
      paths:
      - backend:
          service:
            name: httpd
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific

# precisa no hosts: nginx.kelsen.com e httpd.kelsen.com
# curl 192.168.0.240 -H "Host: nginx.kelsen.com" -L -k -v