apiVersion: v1
kind: Pod
metadata:
  name: nginx-k8s
spec:
  containers:
    - name: nginx-k8s
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: mydata
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"

  initContainers:
    - name: git-k8s
      image: alpine/git
      args:
        - clone
        - --single-branch
        - --
        - https://github.com/jhawithu/k8s-nginx.git
        - /data
      volumeMounts:
        - mountPath: /data
          name: mydata
      resources:
        requests:
          memory: "32Mi"
          cpu: "100m"
        limits:
          memory: "64Mi"
          cpu: "200m"

  volumes:
    - name: mydata
      emptyDir: {}

